# Generated by Django 5.1.6 on 2025-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='delivery',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
